### Here I will try running RRCF parallely and create the final dataset that the agent would see

In [1]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path
from joblib import Parallel, delayed

In [2]:
current_dir = Path().cwd()
project_root = current_dir.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
    print('Done')

Done


In [3]:
from src.sync.RRCF_TS_anomaly_detection import *
from src.utils.save_data import *
from src.sync.Feature_Transformation import feature_engineering, compute_speaker_median_pitch, get_speaker_timings

In [4]:
path = project_root / "data" / "processed" / "merge" / "final_smooth_rz_data.parquet"
df=load_df_parquet_safe(path=str(path))
path = project_root / "data" / "processed" / "merge" / "avw_merged_2.parquet"
non_normfe_df = load_df_parquet_safe(path=str(path))

In [5]:
df.head()

Time  blink_intensity_smooth_rz  gaze_magnitude_smooth_rz  \
0   0.0                   3.571464                  1.555960   
1   0.5                   1.740830                  1.323856   
2   1.0                   1.297544                  1.195807   
3   1.5                   1.004625                  0.428483   
4   2.0                   1.322258                  1.213327   

   jaw_magnitude_smooth_rz  smile_intensity_smooth_rz  loudness_db_smooth_rz  \
0                -0.351862                   1.418536                    NaN   
1                -0.425948                   1.438164                    NaN   
2                -0.627946                   1.056126                    NaN   
3                -0.742188                   0.602340                    NaN   
4                -0.828038                   0.355089                    NaN   

   pitch_relative_st_smooth_rz  pitch_expressiveness_st_smooth_rz  \
0                          NaN                                NaN   
1                          NaN                                NaN   
2                          NaN                                NaN   
3                          NaN                                NaN   
4                          NaN                                NaN   

   wps_smooth_rz              words     text_concat speaker  \
0            NaN  [We're, starting]  We're starting    None   
1            NaN        [now., [*]]        now. [*]       A   
2            NaN               None                       A   
3            NaN      [So, welcome]      So welcome       A   
4            NaN          [to, the]          to the       A   

   filler_percentage  pause_percent_pr  
0           0.064433          0.079177  
1           0.064433          0.079177  
2           0.064433          0.079177  
3           0.064433          0.079177  
4           0.064433          0.079177

In [6]:
feature_cols = [
    ('blink_intensity_smooth_rz', 'ui'),
    ('gaze_magnitude_smooth_rz', 'ui'),
    ('jaw_magnitude_smooth_rz', 'ui'),
    ('smile_intensity_smooth_rz', 'ui'),
    ('loudness_db_smooth_rz', 'ud'),
    ('pitch_relative_st_smooth_rz', 'ud'),
    ('pitch_expressiveness_st_smooth_rz', 'ud'),
    ('wps_smooth_rz', 'ud'),
    ('filler_percentage', 'ud'),
    ('pause_percent_pr', 'ud'),
]

features = {}
feat_id = {}
for name, type in feature_cols:
    f_id, vector = get_data_ready(data=df, features=[name], type=type)
    features[name] = vector
    feat_id[name] = f_id

In [7]:
for key, value in features.items():
    print(value)

[[3.57146417]
 [1.74083022]
 [1.29754446]
 ...
 [1.6549074 ]
 [1.252199  ]
 [1.04397284]]
[[1.55595991]
 [1.3238559 ]
 [1.19580709]
 ...
 [1.07019098]
 [0.47603773]
 [0.01574653]]
[[-0.35186165]
 [-0.42594774]
 [-0.62794575]
 ...
 [-0.90239459]
 [-0.90098368]
 [-0.89959585]]
[[ 1.41853557e+00]
 [ 1.43816411e+00]
 [ 1.05612625e+00]
 ...
 [ 2.40739112e-01]
 [ 8.45211635e-04]
 [-1.89532529e-01]]
[[-0.39149598]
 [-1.81300585]
 [-1.78566912]
 ...
 [ 0.50776887]
 [ 0.0872767 ]
 [-1.10199763]]
[[-0.67413378]
 [-0.69538963]
 [-0.62424157]
 ...
 [-0.66407274]
 [-1.09142559]
 [-0.93226954]]
[[ 0.3390234 ]
 [-0.34631684]
 [-1.44226786]
 ...
 [-0.53677324]
 [-0.70190335]
 [-1.69625822]]
[[-3.21992348]
 [-3.21992348]
 [-2.49393394]
 ...
 [ 1.21875057]
 [ 2.12852661]
 [ 0.60039801]]
[[ 0.06443299]
 [ 0.06443299]
 [ 0.06443299]
 ...
 [13.46649485]
 [13.46649485]
 [13.46649485]]
[[0.07917656]
 [0.07917656]
 [0.07917656]
 ...
 [9.58036421]
 [9.58036421]
 [9.65954078]]


In [8]:
results = Parallel(n_jobs=-1)(
    delayed(run_rrcf)(
        features=value,
        shingle=10
    )
    for _, value in features.items()
)

In [9]:
anomaly_scores = {key:pd.DataFrame(value, index=feat_id[key], columns=['anomaly_scores']) for key, value in zip([feature[0] for feature in feature_cols], results)}

In [10]:
indexes = df.index

In [11]:
df[df['Time'] == 2.5].index.item()

5

In [12]:
anomaly_scores['blink_intensity_smooth_rz']['anomaly_scores']

0       0.000000
1       1.000000
2       1.175000
3       1.450000
4       1.025000
          ...   
1259    4.135224
1260    5.072007
1261    2.844137
1262    3.410219
1263    3.707985
Name: anomaly_scores, Length: 1264, dtype: float64

In [13]:
for key, value in anomaly_scores.items():
    n_sigma = adaptive_n_sigma(anomaly_scores=value['anomaly_scores'])
    # print(n_sigma)
    threshold = get_threshold_mad(scores=value['anomaly_scores'], n_sigma=n_sigma)
    # print(threshold)
    value['is_anomaly'] = value['anomaly_scores'] > threshold
    
    value.loc[value[value['is_anomaly']].index, ['anomaly_index']] = value[value['is_anomaly']].index.map(lambda x: int(indexes.get_loc(x)))
    # value['anomaly_index'] = value['anomaly_index'].astype("Int64")

In [14]:
anomaly_scores

{'blink_intensity_smooth_rz':       anomaly_scores  is_anomaly  anomaly_index
 0           0.000000       False            NaN
 1           1.000000       False            NaN
 2           1.175000       False            NaN
 3           1.450000       False            NaN
 4           1.025000       False            NaN
 ...              ...         ...            ...
 1259        4.135224       False            NaN
 1260        5.072007       False            NaN
 1261        2.844137       False            NaN
 1262        3.410219       False            NaN
 1263        3.707985       False            NaN
 
 [1264 rows x 3 columns],
 'gaze_magnitude_smooth_rz':       anomaly_scores  is_anomaly  anomaly_index
 0           0.000000       False            NaN
 1           1.000000       False            NaN
 2           1.475000       False            NaN
 3           2.575000       False            NaN
 4           1.050000       False            NaN
 ...              ...         ...

In [15]:
anomaly_scores['blink_intensity_smooth_rz']['is_anomaly'] == True

0       False
1       False
2       False
3       False
4       False
        ...  
1259    False
1260    False
1261    False
1262    False
1263    False
Name: is_anomaly, Length: 1264, dtype: bool

In [16]:
c_anomalous = {}
for key, value in anomaly_scores.items():
    pass_df = pd.DataFrame(df.loc[(value[value['is_anomaly'] == True]).index, 'Time'], columns=['Time'])
    pass_df['anomaly_index'] = value.loc[(value[value['is_anomaly'] == True]).index, 'anomaly_index']
    # print(pass_df)
    
    c_anomalous[key] = get_anomalous_time_ranges(anomalies_time=pass_df)

In [17]:
c_anomalous

{'blink_intensity_smooth_rz': [[78, 79, 80, 81],
  [292, 295, 296, 298],
  [330, 331, 332, 333],
  [586, 588, 590],
  [602, 603, 604],
  [620, 622, 624],
  [815, 816, 817, 818, 819, 820, 821, 822],
  [852, 853],
  [875, 878, 879, 880, 881],
  [1062, 1063],
  [1114, 1115, 1116],
  [1145, 1146, 1147, 1148, 1152, 1153, 1154, 1155, 1158, 1160],
  [1169, 1171],
  [1196, 1197, 1198, 1199, 1200, 1204, 1206]],
 'gaze_magnitude_smooth_rz': [[148, 149, 150, 151],
  [258, 259, 260, 264],
  [328, 330, 331, 332, 333],
  [387, 388],
  [424, 425, 426, 427],
  [471, 472, 473, 474, 475, 476],
  [513, 515, 516],
  [569, 570, 571, 572, 573],
  [793, 795, 796, 799, 800, 801, 802],
  [957, 958, 959],
  [966, 967],
  [983, 987],
  [1061, 1062, 1063],
  [1073, 1074, 1075, 1076],
  [1162, 1164, 1165],
  [1208,
   1209,
   1210,
   1211,
   1212,
   1213,
   1214,
   1215,
   1216,
   1217,
   1218,
   1219,
   1220,
   1221]],
 'jaw_magnitude_smooth_rz': [[27, 28, 29],
  [71, 72],
  [106, 108, 110],
  [124, 1

In [75]:
anomaly_scores['blink_intensity_smooth_rz']['anomaly_index']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1259   NaN
1260   NaN
1261   NaN
1262   NaN
1263   NaN
Name: anomaly_index, Length: 1264, dtype: float64

In [18]:
anomalies = {key: list(value['anomaly_index'][value['anomaly_index'].notna()]) for key, value in anomaly_scores.items()}

In [ ]:
# anomalies = {key: list(map(int, value)) for key, value in anomalies}
anomalies

In [26]:
non_normfe_df.columns

Index(['Time', 'words', 'text_concat', 'h_ratio', 'v_ratio', '_neutral',
       'browDownLeft', 'browDownRight', 'browInnerUp', 'browOuterUpLeft',
       'browOuterUpRight', 'cheekPuff', 'cheekSquintLeft', 'cheekSquintRight',
       'eyeBlinkLeft', 'eyeBlinkRight', 'eyeLookDownLeft', 'eyeLookDownRight',
       'eyeLookInLeft', 'eyeLookInRight', 'eyeLookOutLeft', 'eyeLookOutRight',
       'eyeLookUpLeft', 'eyeLookUpRight', 'eyeSquintLeft', 'eyeSquintRight',
       'eyeWideLeft', 'eyeWideRight', 'jawForward', 'jawLeft', 'jawOpen',
       'jawRight', 'mouthClose', 'mouthDimpleLeft', 'mouthDimpleRight',
       'mouthFrownLeft', 'mouthFrownRight', 'mouthFunnel', 'mouthLeft',
       'mouthLowerDownLeft', 'mouthLowerDownRight', 'mouthPressLeft',
       'mouthPressRight', 'mouthPucker', 'mouthRight', 'mouthRollLower',
       'mouthRollUpper', 'mouthShrugLower', 'mouthShrugUpper',
       'mouthSmileLeft', 'mouthSmileRight', 'mouthStretchLeft',
       'mouthStretchRight', 'mouthUpperUpLeft', 'mo

In [31]:
cols = ['h_ratio', 'v_ratio', '_neutral',
       'browDownLeft', 'browDownRight', 'browInnerUp', 'browOuterUpLeft',
       'browOuterUpRight', 'cheekPuff', 'cheekSquintLeft', 'cheekSquintRight',
       'eyeBlinkLeft', 'eyeBlinkRight', 'eyeLookDownLeft', 'eyeLookDownRight',
       'eyeLookInLeft', 'eyeLookInRight', 'eyeLookOutLeft', 'eyeLookOutRight',
       'eyeLookUpLeft', 'eyeLookUpRight', 'eyeSquintLeft', 'eyeSquintRight',
       'eyeWideLeft', 'eyeWideRight', 'jawForward', 'jawLeft', 'jawOpen',
       'jawRight', 'mouthClose', 'mouthDimpleLeft', 'mouthDimpleRight',
       'mouthFrownLeft', 'mouthFrownRight', 'mouthFunnel', 'mouthLeft',
       'mouthLowerDownLeft', 'mouthLowerDownRight', 'mouthPressLeft',
       'mouthPressRight', 'mouthPucker', 'mouthRight', 'mouthRollLower',
       'mouthRollUpper', 'mouthShrugLower', 'mouthShrugUpper',
       'mouthSmileLeft', 'mouthSmileRight', 'mouthStretchLeft',
       'mouthStretchRight', 'mouthUpperUpLeft', 'mouthUpperUpRight',
       'noseSneerLeft', 'noseSneerRight']

In [32]:
non_normfe_df[cols] = non_normfe_df[cols].ffill()

In [33]:
non_normfe_df[non_normfe_df['jawOpen'].isna()]

Empty DataFrame
Columns: [Time, words, text_concat, h_ratio, v_ratio, _neutral, browDownLeft, browDownRight, browInnerUp, browOuterUpLeft, browOuterUpRight, cheekPuff, cheekSquintLeft, cheekSquintRight, eyeBlinkLeft, eyeBlinkRight, eyeLookDownLeft, eyeLookDownRight, eyeLookInLeft, eyeLookInRight, eyeLookOutLeft, eyeLookOutRight, eyeLookUpLeft, eyeLookUpRight, eyeSquintLeft, eyeSquintRight, eyeWideLeft, eyeWideRight, jawForward, jawLeft, jawOpen, jawRight, mouthClose, mouthDimpleLeft, mouthDimpleRight, mouthFrownLeft, mouthFrownRight, mouthFunnel, mouthLeft, mouthLowerDownLeft, mouthLowerDownRight, mouthPressLeft, mouthPressRight, mouthPucker, mouthRight, mouthRollLower, mouthRollUpper, mouthShrugLower, mouthShrugUpper, mouthSmileLeft, mouthSmileRight, mouthStretchLeft, mouthStretchRight, mouthUpperUpLeft, mouthUpperUpRight, noseSneerLeft, noseSneerRight, audio_rms(volumn), audio_pitch_avg, audio_pitch_var(expressiveness), is_silent, speaker, filler_percentage, pause_percent_pr]
Index: []

[0 rows x 64 columns]

In [20]:
speaker_timmings = get_speaker_timings(speaker_times=df[['Time', 'speaker']], speaker='B')

In [20]:
audio_path = project_root / "data" / "raw" / "Interview_2.wav"
median = compute_speaker_median_pitch(audio_path=str(audio_path), speaker_segments=speaker_timmings)

In [21]:
median = 158.74

In [34]:
final_dataframe = feature_engineering(mode="evaluation", c_anomalies=c_anomalous, anomalies=anomalies, df=non_normfe_df, norm_rz_df=df, speaker_median_pitch=median, speaker='B')

In [39]:
final_dataframe.iloc[20:40]

blinking_data  \
20  {'intensity': None, 'asymmetry': None, 'is_bli...   
21  {'intensity': None, 'asymmetry': None, 'is_bli...   
22  {'intensity': None, 'asymmetry': None, 'is_bli...   
23  {'intensity': None, 'asymmetry': None, 'is_bli...   
24  {'intensity': None, 'asymmetry': None, 'is_bli...   
25  {'intensity': None, 'asymmetry': None, 'is_bli...   
26  {'intensity': None, 'asymmetry': None, 'is_bli...   
27  {'intensity': None, 'asymmetry': None, 'is_bli...   
28  {'intensity': None, 'asymmetry': None, 'is_bli...   
29  {'intensity': None, 'asymmetry': None, 'is_bli...   
30  {'intensity': None, 'asymmetry': None, 'is_bli...   
31  {'intensity': None, 'asymmetry': None, 'is_bli...   
32  {'intensity': None, 'asymmetry': None, 'is_bli...   
33  {'intensity': None, 'asymmetry': None, 'is_bli...   
34  {'intensity': None, 'asymmetry': None, 'is_bli...   
35  {'intensity': None, 'asymmetry': None, 'is_bli...   
36  {'intensity': None, 'asymmetry': None, 'is_bli...   
37  {'intensity': None, 'asymmetry': None, 'is_bli...   
38  {'intensity': None, 'asymmetry': None, 'is_bli...   
39  {'intensity': None, 'asymmetry': None, 'is_bli...   

                                            gaze_data  \
20  {'horizontal_deviation': None, 'vertical_devia...   
21  {'horizontal_deviation': None, 'vertical_devia...   
22  {'horizontal_deviation': None, 'vertical_devia...   
23  {'horizontal_deviation': None, 'vertical_devia...   
24  {'horizontal_deviation': None, 'vertical_devia...   
25  {'horizontal_deviation': None, 'vertical_devia...   
26  {'horizontal_deviation': None, 'vertical_devia...   
27  {'horizontal_deviation': None, 'vertical_devia...   
28  {'horizontal_deviation': None, 'vertical_devia...   
29  {'horizontal_deviation': None, 'vertical_devia...   
30  {'horizontal_deviation': None, 'vertical_devia...   
31  {'horizontal_deviation': None, 'vertical_devia...   
32  {'horizontal_deviation': None, 'vertical_devia...   
33  {'horizontal_deviation': None, 'vertical_devia...   
34  {'horizontal_deviation': None, 'vertical_devia...   
35  {'horizontal_deviation': None, 'vertical_devia...   
36  {'horizontal_deviation': None, 'vertical_devia...   
37  {'horizontal_deviation': None, 'vertical_devia...   
38  {'horizontal_deviation': None, 'vertical_devia...   
39  {'horizontal_deviation': None, 'vertical_devia...   

                                    jaw_movement_data  \
20  {'open': 0.0003300155804026872, 'lateral': Non...   
21  {'open': 9.470622899243608e-05, 'lateral': Non...   
22  {'open': 0.06632930040359497, 'lateral': None,...   
23  {'open': 0.0005459068925119936, 'lateral': Non...   
24  {'open': 0.0005173762328922749, 'lateral': Non...   
25  {'open': 0.018747227266430855, 'lateral': None...   
26  {'open': 0.041224658489227295, 'lateral': None...   
27  {'open': 0.09769998490810394, 'lateral': -0.00...   
28  {'open': 0.14945782721042633, 'lateral': -0.06...   
29  {'open': 0.09816937148571014, 'lateral': -0.01...   
30  {'open': 0.00101134879514575, 'lateral': None,...   
31  {'open': 0.010108656249940395, 'lateral': None...   
32  {'open': 0.008240586146712303, 'lateral': None...   
33  {'open': 0.042617782950401306, 'lateral': None...   
34  {'open': 0.01866837777197361, 'lateral': None,...   
35  {'open': 0.05222214385867119, 'lateral': None,...   
36  {'open': 0.03480718657374382, 'lateral': None,...   
37  {'open': 0.005594722460955381, 'lateral': None...   
38  {'open': 0.03743157535791397, 'lateral': None,...   
39  {'open': 0.01261579804122448, 'lateral': None,...   

                                           smile_data  \
20  {'intensity': 1.970937121775762e-05, 'asymmetr...   
21  {'intensity': 0.0026545619226879145, 'asymmetr...   
22  {'intensity': 5.0152379290580026e-05, 'asymmet...   
23  {'intensity': 2.1747304715802328e-05, 'asymmet...   
24  {'intensity': 1.3380005162844098e-05, 'asymmet...   
25  {'intensity': 1.3724788826152689e-05, 'asymmet...   
26  {'intensity': 1.0467591879148584e-05, 'asym

In [42]:
non_normfe_df['Time'].iloc[c_anomalous['gaze_magnitude_smooth_rz'][0]]

148    74.0
149    74.5
150    75.0
151    75.5
Name: Time, dtype: float64

In [53]:
non_normfe_df.columns

Index(['Time', 'words', 'text_concat', 'h_ratio', 'v_ratio', '_neutral',
       'browDownLeft', 'browDownRight', 'browInnerUp', 'browOuterUpLeft',
       'browOuterUpRight', 'cheekPuff', 'cheekSquintLeft', 'cheekSquintRight',
       'eyeBlinkLeft', 'eyeBlinkRight', 'eyeLookDownLeft', 'eyeLookDownRight',
       'eyeLookInLeft', 'eyeLookInRight', 'eyeLookOutLeft', 'eyeLookOutRight',
       'eyeLookUpLeft', 'eyeLookUpRight', 'eyeSquintLeft', 'eyeSquintRight',
       'eyeWideLeft', 'eyeWideRight', 'jawForward', 'jawLeft', 'jawOpen',
       'jawRight', 'mouthClose', 'mouthDimpleLeft', 'mouthDimpleRight',
       'mouthFrownLeft', 'mouthFrownRight', 'mouthFunnel', 'mouthLeft',
       'mouthLowerDownLeft', 'mouthLowerDownRight', 'mouthPressLeft',
       'mouthPressRight', 'mouthPucker', 'mouthRight', 'mouthRollLower',
       'mouthRollUpper', 'mouthShrugLower', 'mouthShrugUpper',
       'mouthSmileLeft', 'mouthSmileRight', 'mouthStretchLeft',
       'mouthStretchRight', 'mouthUpperUpLeft', 'mo

In [54]:
final_dataframe[['Time', 'words', 'text_concat']] = non_normfe_df[['Time', 'words', 'text_concat']]

In [55]:
final_dataframe

blinking_data  \
0     {'intensity': None, 'asymmetry': None, 'is_bli...   
1     {'intensity': None, 'asymmetry': None, 'is_bli...   
2     {'intensity': None, 'asymmetry': None, 'is_bli...   
3     {'intensity': None, 'asymmetry': None, 'is_bli...   
4     {'intensity': None, 'asymmetry': None, 'is_bli...   
...                                                 ...   
1259  {'intensity': None, 'asymmetry': None, 'is_bli...   
1260  {'intensity': None, 'asymmetry': None, 'is_bli...   
1261  {'intensity': None, 'asymmetry': None, 'is_bli...   
1262  {'intensity': None, 'asymmetry': None, 'is_bli...   
1263  {'intensity': None, 'asymmetry': None, 'is_bli...   

                                              gaze_data  \
0     {'horizontal_deviation': None, 'vertical_devia...   
1     {'horizontal_deviation': None, 'vertical_devia...   
2     {'horizontal_deviation': None, 'vertical_devia...   
3     {'horizontal_deviation': None, 'vertical_devia...   
4     {'horizontal_deviation': None, 'vertical_devia...   
...                                                 ...   
1259  {'horizontal_deviation': None, 'vertical_devia...   
1260  {'horizontal_deviation': None, 'vertical_devia...   
1261  {'horizontal_deviation': None, 'vertical_devia...   
1262  {'horizontal_deviation': None, 'vertical_devia...   
1263  {'horizontal_deviation': None, 'vertical_devia...   

                                      jaw_movement_data  \
0     {'open': 0.023826630786061287, 'lateral': None...   
1     {'open': 0.01953260414302349, 'lateral': None,...   
2     {'open': 0.0008870773017406464, 'lateral': Non...   
3     {'open': 0.0015012087533250451, 'lateral': Non...   
4     {'open': 0.00043307070154696703, 'lateral': No...   
...                                                 ...   
1259  {'open': 0.0018719969084486365, 'lateral': Non...   
1260  {'open': 0.0018371319165453315, 'lateral': Non...   
1261  {'open': 0.001750032533891499, 'lateral': None...   
1262  {'open': 0.0019191708415746689, 'lateral': Non...   
1263  {'open': 0.0019407219951972365, 'lateral': Non...   

                                             smile_data loudness_data  \
0     {'intensity': 0.00020072988331669704, 'asymmet...           NaN   
1     {'intensity': 0.00020793307342685806, 'asymmet...           NaN   
2     {'intensity': 6.213216343535776e-05, 'asymmetr...           NaN   
3     {'intensity': 4.647151249770331e-06, 'asymmetr...           NaN   
4     {'intensity': 4.343396951611567e-05, 'asymmetr...           NaN   
...                                                 ...           ...   
1259  {'intensity': 2.4302891581129413e-05, 'asymmet...           NaN   
1260  {'intensity': 2.613913233808773e-05, 'asymmetr...           NaN   
1261  {'intensity': 2.566660534313314e-05, 'asymmetr...           NaN   
1262  {'intensity': 1.664540692782879e-05, 'asymmetr...           NaN   
1263  {'intensity': 1.5253251348568142e-05, 'asymmet...           NaN   

     average_pitch_data pitch_standard_deviation words_per_sec  \
0                   NaN                      NaN           NaN   
1                   NaN                      NaN           NaN   
2                   NaN                      NaN           NaN   
3                   NaN                      NaN           NaN   
4                   NaN                      NaN           NaN   
...                 ...                      ...           ...   
1259                NaN                      NaN           NaN   
1260                NaN                      NaN           NaN   
1261                NaN                      NaN           NaN   
1262                NaN                      NaN           NaN   
1263                NaN                      NaN           NaN   

     filler_words_usage pauses_taken   Time                       words  \
0                   NaN          NaN    0.0           [We're, starting]   
1                   NaN          NaN    0.5                 [now., [*]]   
2                   

In [56]:
path = project_root / "data" / "processed" / "merge" / "final_dataframe.parquet"
save_df_parquet_safe(df=final_dataframe, path=str(path))

Saved Parquet: c:\Users\BIT\Desktop\mmr\data\processed\merge\final_dataframe.parquet
Saved schema: c:\Users\BIT\Desktop\mmr\data\processed\merge\final_dataframe.parquet.schema.json
